# -*- coding: utf-8 -*-
"""Face_recognition (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biiun4tayN7G_nWHvpm3hbHykUCX0E5z
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install mtcnn

!pip install lz4

import cv2 as cv
import os
import tensorflow as ts
import numpy as np
import matplotlib.pyplot as plt
os.environ["TF_CPP_MIN_LOG_LEVEL"]="2"

img=cv.imread("/content/drive/MyDrive/Dataset/Prakash/Copy of WhatsApp Image 2026-01-02 at 10.23.44 AM.jpeg")

img=cv.cvtColor(img,cv.COLOR_BGR2RGB)
plt.imshow(img)

from mtcnn import MTCNN
detector=MTCNN()
results=detector.detect_faces(img)

results

x,y,w,z=results[0]["box"]

img=cv.rectangle(img,(x,y),(x+w,y+z),(0,255,0),2)

plt.imshow(img)

my_face=img[y:y+z,x:x+w]
my_face=cv.resize(my_face,(160,160))
plt.imshow(my_face)

my_face

import joblib

# Save the label encoder to a file
# joblib.dump(encoder, 'label_encoder.pkl') # Commented out as encoder is defined and saved later

class FACELOADING:
    def __init__(self, directory):
        self.directory = directory
        self.target_size = (160,160)
        self.X = []
        self.Y = []
        self.detector = MTCNN()


    def extract_face(self, filename):
        img = cv.imread(filename)
        img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
        x,y,w,h = self.detector.detect_faces(img)[0]['box']
        x,y = abs(x), abs(y)
        face = img[y:y+h, x:x+w]
        face_arr = cv.resize(face, self.target_size)
        return face_arr


    def load_faces(self, dir):
        FACES = []
        for im_name in os.listdir(dir):
            try:
                path = dir + im_name
                single_face = self.extract_face(path)
                FACES.append(single_face)
            except Exception as e:
                pass
        return FACES

    def load_classes(self):
        for sub_dir in os.listdir(self.directory):
            path = self.directory +'/'+ sub_dir+'/'
            FACES = self.load_faces(path)
            labels = [sub_dir for _ in range(len(FACES))]
            print(f"Loaded successfully: {len(labels)}")
            self.X.extend(FACES)
            self.Y.extend(labels)

        return np.asarray(self.X), np.asarray(self.Y)


    def plot_images(self):
        plt.figure(figsize=(18,16))
        for num,image in enumerate(self.X):
            ncols = 3
            nrows = len(self.Y)//ncols + 1
            plt.subplot(nrows,ncols,num+1)
            plt.imshow(image)
            plt.axis('off')

faceloading=FACELOADING("/content/drive/MyDrive/Dataset")
X,Y=faceloading.load_classes()

faceloading.plot_images()

"""FACE_NET

"""

!pip install keras-facenet

from keras_facenet import FaceNet
embedder = FaceNet()

def get_embedding(face_img):
    face_img = face_img.astype('float32') # 3D(160x160x3)
    face_img = np.expand_dims(face_img, axis=0)
    # 4D (Nonex160x160x3)
    yhat= embedder.embeddings(face_img)
    return yhat[0] # 512D image (1x1x512)

EMBEDDED_X = []

for img in X:
    EMBEDDED_X.append(get_embedding(img))

EMBEDDED_X = np.asarray(EMBEDDED_X)

np.savez_compressed('faces_embeddings_done_4classes.npz', EMBEDDED_X, Y)

"""SVM Model"""

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)

plt.plot(EMBEDDED_X[0])
plt.ylabel(Y[0])

Y

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(EMBEDDED_X, Y, shuffle=True, random_state=17)

from sklearn.svm import SVC
model = SVC(kernel='rbf', probability=True)
model.fit(X_train, Y_train)

import joblib
from google.colab import files

# 1. Save the Label Encoder object
# In your code, 'encoder' is the variable used to fit the labels [cite: 264]
joblib.dump(encoder, 'label_encoder.pkl')

# 2. Save the SVM Model as well (to ensure versions match)
joblib.dump(model, 'face_recognition_model.pkl')

# 3. Trigger the browser download to your Mac
files.download('label_encoder.pkl')
files.download('face_recognition_model.pkl')

ypreds_train = model.predict(X_train)
ypreds_test = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_score(Y_train, ypreds_train)

accuracy_score(Y_test,ypreds_test)

from sklearn.metrics import ConfusionMatrixDisplay

# 1. Create the figure
fig, ax = plt.subplots(figsize=(8, 6))

# 2. Plot the confusion matrix with display_labels
disp = ConfusionMatrixDisplay.from_predictions(
    Y_test,
    ypreds_test,
    display_labels=encoder.classes_,  # This tells the plot to use the original names
    cmap=plt.cm.Blues,
    ax=ax,
    colorbar=True
)

# 3. Add titles and labels
plt.title("Confusion Matrix: SVM Face Recognition")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.xticks(rotation=45) # Optional: rotates names if they overlap
plt.show()